import numpy as np
from datetime import datetime
from enum import Enum

class Layout:
    '''Describes the format and layout of time superimposed on video image'''

    def __init__(self, **kwargs):
        '''Create a new layout.

        By default the layout corresponds to what is generated by Axis IP
        cameras with large font settings.

        Kwargs
        ------
        digit_origin : array-like
            x,y coordinates of first digit in image
        digit_shape: array-like
            Height and width of individual digits.
        digit_stride: array-like
            Strides in x and y direction to reach next digit location.
        digits: array-like
            Describes the locations and semantics of each digit. For example
            the time format `HH:MM:SS.FF` is described by 
                [0,1,3,4,6,7,9,10]           
        '''

        self.digit_origin = np.asarray(kwargs.pop('digit_origin', [22, 6]))
        self.digit_shape = np.asarray(kwargs.pop('digit_shape', [21, 14]))
        self.digit_stride = np.asarray(kwargs.pop('digit_stride', [4+self.digit_shape[1], 0])) 
        self.digits = kwargs.pop('digits', [0,1,3,4,6,7,9,10])
        self.ndigits = len(self.digits)

        
        # Image slices for each digit location
        self.slicesx = []
        self.slicesy = []
        for i in self.digits:
            xy = self.digit_origin + i*self.digit_stride            
            self.slicesx.append(slice(xy[0], xy[0] + self.digit_shape[1]))
            self.slicesy.append(slice(xy[1], xy[1] + self.digit_shape[0]))

    def build_time(self, dtime):
        '''Returns a datetime object from detected time digit sequence.'''
        d = datetime.now()
        h = 10*dtime[0] + dtime[1]
        m = 10*dtime[2] + dtime[3]
        s = 10*dtime[4] + dtime[5]
        micro = (10*dtime[6] + dtime[7])*int(1e4)
        return d.replace(hour=h, minute=m, second=s, microsecond=micro)        


axisLayoutLarge = Layout()
axisLayoutSmall = Layout(digit_origin=[16,4], digit_shape=[16,10], digit_stride=[13,0])
        
layout_names = {
    'axis_small' : axisLayoutSmall,
    'axis_large' : axisLayoutLarge
}
    
if __name__ == '__main__':
    import numpy as np
    import cv2
    import argparse
    import glob
    import os

    
    parser = argparse.ArgumentParser(description='Train time detector')
    parser.add_argument('indir', help='Directory containing images')    
    parser.add_argument('--layout', help='Time layout name', default='axis_large')
    args = parser.parse_args()

    f = glob.glob(os.path.join(args.indir, '*.png'))[0]
    img = cv2.imread(f)

    l = layout_names[args.layout]
    print(l.digit_origin)
    print(l.digit_shape)
    print(l.digit_stride)

    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1, l.ndigits)
    for i in range(l.ndigits):
        axs[i].imshow(img[l.slicesy[i], l.slicesx[i],0], origin='upper')
        axs[i].axis('off')
    plt.show()


    